language: python

cache: pip

install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
  - poetry install -v

script: poetry run pytest -v

notifications:
  email: false
